package com.axisrooms.KnightsTemplar.enums;

public enum ConfigProperties {

	URL, BROWSER, USERNAME, PASSWORD, OVERRIDEREPORTS,

	PASSEDSTEPSCREENSHOT, FAILEDSTEPSCREENSHOT, SKIPPEDSTEPSCREENSHOT

}
